# Generated by Django 6.0.3 on 2026-04-14 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_ticket_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.URLField(max_length=500),
        ),
    ]
